site_name: My Docs
theme:
  name: material

nav:
  - Service一覧: V0/Service.md
  - 1.Account: 
    - 1.1. 登録: V0/V0AccountRegister.md
    - 1.2. 取得: V0/V0AccountGetProfile.md
    - 1.3. 更新: V0/V0AccountUpdateProfile.md
    - 1.4. 削除: V0/V0AccountDelete.md
  - 2.Auth:
    - 2.1. 認証認可: V0/V0AccountAuthenticate.md
    - 2.2. セッション終了: V0/V0AccountUnauthenticate.md
    - 2.3. トークン確認: V0/V0AccountVerifyToken.md
  - 3.Organization:
    - 3.1. Chats:
      - 3.1.1. リストを取得: V0/V0ListChats.md
      - 3.1.2. 取得: V0/V0GetChat.md
      - 3.1.3. 作成: V0/V0CreateChat.md
      - 3.1.4. 更新: V0/V0UpdateChat.md
      - 3.1.5. 削除: V0/V0DeleteChat.md
    - 3.2. Infos:
      - 3.2.1. 取得: V0/V0InfoGet.md
      - 3.2.2. 作成: V0/V0InfoCreate.md
      - 3.2.3. 更新: V0/V0InfoUpdate.md
      - 3.2.4. 削除: V0/V0DeleteInfo.md
    - 3.3. Members:
      - 3.3.1. リストを取得: V0/V0ListMembers.md
      - 3.3.2. 取得: V0/V0GetMember.md
      - 3.3.3. 参加: V0/V0JoinMember.md
      - 3.3.4. 退出: V0/V0LeaveMember.md
    - 3.4. Roles:
      - 3.4.1. リストを取得: V0/V0ListRoles.md
      - 3.4.2. 取得: V0/V0GetRole.md
      - 3.4.3. 作成: V0/V0CreateRole.md
      - 3.4.4. 更新: V0/V0UpdateRole.md
      - 3.4.5. 削除: V0/V0DeleteRole.md
    - 3.5. Messages:
      - 3.5.1. リストを取得: V0/V0ListMessages.md
      - 3.5.2. 取得: V0/V0GetMessage.md
      - 3.5.3. 作成: V0/V0CreateMessage.md
      - 3.5.4. 更新: V0/V0UpdateMessage.md
      - 3.5.5. 削除: V0/V0DeleteMessage.md