site_name: My Docs
theme:
  name: material

nav:
  - Service一覧: V0/Service.md
  - 1.Account: 
    - 1.1. 登録: V0/V0AccountRegisterRequest.md
    - 1.2. 取得: V0/V0AccountGetProfileRequest.md
    - 1.3. 更新: V0/V0AccountUpdateProfileRequest.md
  - 2.Auth:
    - 2.1. 認証認可: V0/V0AccountAuthenticateRequest.md
  - 3.Organization:
    - 3.1. Chats:
      - 3.1.1. リストを取得: V0/V0ListXRequest.md
      - 3.1.2. 取得と削除: V0/V0GetOrDeleteXRequest.md
      - 3.1.3. 作成: V0/V0CreateChatRequest
      - 3.1.4. 更新: V0/V0UpdateChatRequest
    - 3.2. Infos:
      - 3.2.2. 取得と削除: V0/V0BaseRequest
      - 3.2.3. 作成: V0/V0CreateOrganizationRequest
      - 3.2.4. 更新: V0/V0UpdateOrganizationRequest
      - 3.2.5. 削除: V0/V0BaseRequest
    - 3.3. Members:
      - 3.3.1. リストを取得: V0/V0ListXRequest.md
      - 3.3.2. メンバーを取得: V0/V0GetOrDeleteXRequest.md
      - 3.3.3. メンバーに参加: V0/V0JoinMemberRequest
      - 3.3.4. メンバーを退出: V0/V0LeaveMemberRequest
    - 3.4. Roles:
      - 3.4.1. リストを取得: V0/V0ListXRequest.md
      - 3.4.2. 取得と削除: V0/V0GetOrDeleteXRequest.md
      - 3.4.3. 作成: V0/V0CreateRollRequest
      - 3.4.4. 更新: V0/Role.md
    - 3.5. Messages:
      - 3.5.1. リストを取得: V0/V0ListMessagesRequest
      - 3.5.2. 取得と削除: V0/V0GetOrDeleteMessageRequest
      - 3.5.3. 作成と更新: V0/Message.md